# Generated by Django 4.0 on 2021-12-12 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankingApp', '0002_auto_20211128_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_administrator',
        ),
    ]
