# Generated by Django 3.2.9 on 2021-12-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankingApp', '0003_remove_user_is_administrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='internal_id',
            field=models.CharField(max_length=7),
        ),
    ]
