# Generated by Django 3.2.9 on 2021-12-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankingApp', '0004_alter_user_internal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='internal_id',
            field=models.TextField(max_length=7),
        ),
    ]
