# Generated by Django 3.2.9 on 2021-12-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankingApp', '0006_alter_user_internal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='internal_id',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
