# Generated by Django 3.2.9 on 2021-12-22 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='access',
        ),
        migrations.RemoveField(
            model_name='user',
            name='account',
        ),
        migrations.DeleteModel(
            name='Access',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
